name: "Set up AWS Credentials and Fetch Secrets"
description: "Configures AWS credentials for use in subsequent steps. Fetches secrets from AWS Secrets Manager."

inputs:
  aws_role_to_assume:
    description: "ARN of the IAM role to assume"
    default: "arn:aws:iam::282898975672:role/spacecat-role-github-actions"
    required: true
  secret_ids:
    description: "List of secret IDs to fetch from AWS Secrets Manager"
    default: |
        /spacecat/github-action-secrets
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: ${{ inputs.aws_role_to_assume }}

    - name: Fetch AWS Secrets
      uses: aws-actions/aws-secretsmanager-get-secrets@v2
      with:
        parse-json-secrets: true
        secret-ids: ${{ inputs.secret_ids }}
