configurations-sites-audits-toggle:
  patch:
    tags:
      - configurations-sites-audits
    summary: Enable or disable audits for sites
    description: |
      Use this endpoint to enable or disable specific audit types for your sites.
    operationId: update
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: array
            items:
              type: object
              properties:
                baseURL:
                  $ref: './schemas.yaml#/URL'
                auditType:
                  type: string
                  description: The type of audit to be enabled or disabled.
                  examples:
                    - cwv
                    - 404
                    - broken-backlinks
                enable:
                  type: boolean
                  description: Set to true to enable the audit, or false to disable it.
              required:
                - baseURL
                - auditType
                - enable
    responses:
      '207':
        description: A list of baseURL, the status of the update, and the corresponding site if successful, or the error message if failed.
        content:
          application/json:
            schema:
              $ref: './schemas.yaml#/ConfigurationSitesAuditsUpdateResult'
      '401':
        $ref: './responses.yaml#/401'
      '500':
        $ref: './responses.yaml#/500'
    security:
      - admin_key: [ ]
