latest-configuration:
  get:
    tags:
      - configuration
    summary: Get the latest application configuration
    operationId: getLatestConfiguration
    security:
      - admin_key: [ ]
    responses:
      '200':
        description: The latest application configuration.
        content:
          application/json:
            schema:
              $ref: './schemas.yaml#/Configuration'
      '401':
        $ref: './responses.yaml#/401'
      '404':
        description: Latest configuration not found.
      '500':
        $ref: './responses.yaml#/500'
configuration:
  get:
    tags:
      - configuration
    summary: Get a specific version of the application configuration
    operationId: getConfigurationByVersion
    security:
      - admin_key: [ ]
    parameters:
      - name: version
        in: path
        required: true
        schema:
          type: string
    responses:
      '200':
        description: Specific version of the application configuration.
        content:
          application/json:
            schema:
              $ref: './schemas.yaml#/Configuration'
      '401':
        $ref: './responses.yaml#/401'
      '404':
        $ref: './responses.yaml#/404-configuration-not-found-with-version'
      '500':
        $ref: './responses.yaml#/500'
