organizationId:
  name: organizationId
  description: The organization ID in uuid format
  in: path
  required: true
  schema:
    $ref: './schemas.yaml#/Id'
siteId:
  name: siteId
  description: The site ID in uuid format
  in: path
  required: true
  schema:
    $ref: './schemas.yaml#/Id'
auditedAt:
  name: auditedAt
  description: The date and time of the audit in ISO 8601 format
  in: path
  required: true
  schema:
    $ref: './schemas.yaml#/DateTime'
auditType:
  name: auditType
  description: The type of the audit
  in: path
  required: true
  schema:
    $ref: './schemas.yaml#/AuditType'
deliveryType:
  name: deliveryType
  description: The type of the delivery this site is using
  in: path
  required: true
  schema:
    $ref: './schemas.yaml#/DeliveryType'
base64BaseUrl:
  name: base64BaseUrl
  description: Base64-encoded base URL
  in: path
  required: true
  schema:
    type: string
    format: base64url
ascending:
  name: ascending
  description: Whether to sort ascending or descending
  in: query
  required: false
  schema:
    type: boolean
    default: false
triggerUrl:
  name: url
  description: The URL or Site ID to trigger the audit for
  in: query
  required: true
  schema:
    type: string
triggerType:
  name: type
  description: The type of the audit to trigger
  in: query
  required: true
  schema:
    $ref: './schemas.yaml#/AuditType'
imsOrgId:
  name: imsOrgId
  description: An IMS organization ID
  in: path
  required: true
  schema:
    $ref: './schemas.yaml#/ImsOrganizationId'
hookSecret:
  name: hookSecret
  description: Secret for the incoming webhook
  in: path
  required: true
  schema:
    type: string
keyEventId:
  name: keyEventId
  description: The key event ID in uuid format
  in: path
  required: true
  schema:
    $ref: './schemas.yaml#/Id'
source:
  name: source
  description: The source of the top pages
  in: path
  required: true
  schema:
    type: string
    enum:
      - 'ahrefs'
    example: 'ahrefs'
geo:
  name: geo
  description: The geo of the top pages
  in: path
  required: true
  schema:
    type: string
    example: 'au'
metric:
  name: metric
  description: The name of the site metric
  in: path
  required: true
  schema:
    type: string
    enum:
      - 'organic-traffic'
    example: 'organic-traffic'
