siteId:
  name: siteId
  in: path
  required: true
  schema:
    type: string
auditType:
  name: auditType
  in: path
  required: true
  schema:
    type: string
base64BaseUrl:
  name: base64BaseUrl
  in: path
  required: true
  schema:
    type: string
    format: base64url
triggerUrl:
  name: url
  in: query
  required: true
  schema:
    type: string
triggerType:
  name: type
  in: query
  required: true
  schema:
    type: string
    enum:
      - manual
      - scheduled
      - webhook
