name: "Setup Node & NPM (with cache)"
description: "Checks out code, sets up Node, uses NPM cache, installs dependencies"

runs:
  using: "composite"
  steps:
    - name: Set up Node
      uses: actions/setup-node@v5
      with:
        node-version-file: '.nvmrc'

    - name: Get npm cache directory
      id: npm-cache-dir
      run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Set up NPM Cache
      uses: actions/cache@v4
      id: npm-cache
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        # No restore-keys - only use cache with exact package-lock.json match

    - name: Clean node_modules for fresh install
      run: rm -rf node_modules
      shell: bash

    - name: Install dependencies
      run: npm ci
      shell: bash
