name: "Setup Node & NPM (with cache)"
description: "Checks out code, sets up Node, uses NPM cache, installs dependencies"

runs:
  using: "composite"
  steps:
    - name: Set up Node
      uses: actions/setup-node@v5
      with:
        node-version-file: '.nvmrc'

    - name: Get npm cache directory
      id: npm-cache-dir
      run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Set up NPM Cache
      uses: actions/cache@v4
      id: npm-cache
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Configure Git auth for private Mysticat types repo
      run: |
        git config --global url."https://x-access-token:${MYSTICAT_DATA_SERVICE_REPO_READ_TOKEN}@github.com/".insteadOf "https://github.com/"
        git config --global --add url."https://x-access-token:${MYSTICAT_DATA_SERVICE_REPO_READ_TOKEN}@github.com/".insteadOf "ssh://git@github.com/"
        git config --global --add url."https://x-access-token:${MYSTICAT_DATA_SERVICE_REPO_READ_TOKEN}@github.com/".insteadOf "git@github.com:"
      shell: bash

    - name: Install dependencies (only if cache miss)
      run: npm ci
      shell: bash
