name: End-to-end API Tests

on:
  schedule:
    - cron: "0 14 * * *" # Runs daily at 14:00 UTC
  workflow_dispatch: # Allows us to manually trigger the workflow if needed

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [prod] # We can add dev here to run tests on both ci & v1 endpoints

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: 'false'

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'

      - name: Configure Git auth for private repos
        run: |
          git config --global url."https://x-access-token:${MYSTICAT_DATA_SERVICE_REPO_READ_TOKEN}@github.com/".insteadOf "https://github.com/"
        env:
          MYSTICAT_DATA_SERVICE_REPO_READ_TOKEN: ${{ secrets.MYSTICAT_DATA_SERVICE_REPO_READ_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        env:
          ENVIRONMENT: ${{ matrix.environment }}
          AEM_E2E_IMPORT_API_KEY_PROD: ${{ secrets.AEM_E2E_IMPORT_API_KEY_PROD }}
          AEM_E2E_IMPORT_API_KEY_DEV: ${{ secrets.AEM_E2E_IMPORT_API_KEY_DEV }}
          USER_API_KEY: ${{ secrets.USER_API_KEY }}
        run: npm run test-e2e
